import type { DateEntry, Post, Comment, PartnerNameStat, TrendingEntry } from './types';

export const MOCK_ENTRIES: DateEntry[] = [
  { id: '1', userId: 'demo', activityType: 'food_date', amountCents: 8500, currency: 'EUR', partnerDisplayName: 'Sophie', moodScore: 'amazing', entryDate: '2026-05-20', city: 'Berlin', country: 'Germany', howMet: 'hinge', wantSecondDate: 'yes', createdAt: '2026-05-20T19:00:00Z' },
  { id: '2', userId: 'demo', activityType: 'coffee', amountCents: 1200, currency: 'EUR', partnerDisplayName: 'Emma', moodScore: 'happy', entryDate: '2026-05-22', city: 'Berlin', country: 'Germany', howMet: 'bumble', wantSecondDate: 'yes', createdAt: '2026-05-22T11:00:00Z' },
  { id: '3', userId: 'demo', activityType: 'movie', amountCents: 3800, currency: 'EUR', partnerDisplayName: 'Laura', moodScore: 'fun', entryDate: '2026-05-24', city: 'Berlin', country: 'Germany', howMet: 'tinder', wantSecondDate: 'no', createdAt: '2026-05-24T20:00:00Z' },
  { id: '4', userId: 'demo', activityType: 'gift', amountCents: 15000, currency: 'EUR', partnerDisplayName: 'Sophie', moodScore: 'amazing', entryDate: '2026-05-26', city: 'Berlin', country: 'Germany', wantSecondDate: 'together', createdAt: '2026-05-26T18:00:00Z' },
  { id: '5', userId: 'demo', activityType: 'food_date', amountCents: 9200, currency: 'EUR', partnerDisplayName: 'Mia', moodScore: 'happy', entryDate: '2026-05-28', city: 'Berlin', country: 'Germany', howMet: 'hinge', wantSecondDate: 'yes', createdAt: '2026-05-28T20:00:00Z' },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    userId: 'u1',
    displayName: 'u/CafeLover',
    ageRange: '25-34',
    city: 'Berlin',
    postType: 'advice',
    content: 'Pro tip: Coffee dates are underrated. €8 and you actually get to talk, unlike a noisy restaurant. Best dates I\'ve had were over espresso ☕',
    tags: ['Advice', 'Coffee'],
    upvoteCount: 247,
    downvoteCount: 12,
    commentCount: 38,
    createdAt: '2026-05-29T10:00:00Z',
  },
  {
    id: 'p2',
    userId: 'u2',
    displayName: 'u/BerlinFoodie',
    ageRange: '25-34',
    city: 'Berlin',
    postType: 'experience',
    content: 'Just had an amazing dinner date in Berlin, but wow, €95 is a lot for pasta! 😅 Worth it though — the vibe was perfect.',
    tags: ['Experience', 'Berlin', 'Food Date'],
    upvoteCount: 183,
    downvoteCount: 8,
    commentCount: 24,
    createdAt: '2026-05-29T08:30:00Z',
  },
  {
    id: 'p3',
    userId: 'u3',
    displayName: 'u/overthinkr99',
    ageRange: '18-24',
    city: 'Munich',
    postType: 'question',
    content: 'Is spending €400 on a weekend trip for an anniversary normal? My friends say I\'m overspending but it felt right 🤷',
    tags: ['Question', 'Trip', 'Anniversary'],
    upvoteCount: 156,
    downvoteCount: 34,
    commentCount: 67,
    createdAt: '2026-05-28T22:00:00Z',
  },
  {
    id: 'p4',
    userId: 'u4',
    displayName: 'u/observant_dater',
    ageRange: '35-44',
    city: 'Hamburg',
    postType: 'observation',
    content: 'Noticed people\'s spending more on gifts lately. Is it just me or has dating become way more expensive in 2026?',
    tags: ['Observation', 'Gift', 'Trends'],
    upvoteCount: 312,
    downvoteCount: 21,
    commentCount: 89,
    createdAt: '2026-05-28T15:00:00Z',
  },
  {
    id: 'p5',
    userId: 'u5',
    displayName: 'u/HingeHopeful',
    ageRange: '25-34',
    city: 'Frankfurt',
    postType: 'experience',
    content: 'Met someone on Hinge for coffee, ended up talking for 4 hours. €9 has never felt so worth it 😍 Third date next week!',
    tags: ['Experience', 'Coffee', 'Hinge'],
    upvoteCount: 428,
    downvoteCount: 6,
    commentCount: 54,
    createdAt: '2026-05-27T20:00:00Z',
  },
  {
    id: 'p6',
    userId: 'u6',
    displayName: 'u/MovieNightFan',
    ageRange: '18-24',
    city: 'Cologne',
    postType: 'advice',
    content: 'Movie dates are criminally underrated. €25 for two tickets, a shared popcorn, and you have something to talk about after. Perfect formula.',
    tags: ['Advice', 'Movie'],
    upvoteCount: 274,
    downvoteCount: 18,
    commentCount: 42,
    createdAt: '2026-05-27T14:00:00Z',
  },
];

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  p1: [
    { id: 'c1', postId: 'p1', userId: 'u10', displayName: 'u/EspressoLover', content: 'Totally agree. Coffee dates filter out the people who aren\'t really interested in you, just the experience.', upvoteCount: 45, downvoteCount: 2, createdAt: '2026-05-29T10:30:00Z' },
    { id: 'c2', postId: 'p1', userId: 'u11', displayName: 'u/FancyDater', content: 'Disagree. Nothing says "I\'m serious about this" like a proper dinner. Coffee feels like a screening 🤷', upvoteCount: 23, downvoteCount: 15, createdAt: '2026-05-29T11:00:00Z' },
    { id: 'c3', postId: 'p1', userId: 'u12', displayName: 'u/PracticalPatrick', content: 'Coffee is 100% the move for first dates. Low pressure, easy to extend or cut short.', upvoteCount: 67, downvoteCount: 1, createdAt: '2026-05-29T11:30:00Z' },
  ],
  p2: [
    { id: 'c4', postId: 'p2', userId: 'u13', displayName: 'u/BudgetKing', content: '€95 for pasta 😭 Which restaurant? Need to know what to avoid', upvoteCount: 89, downvoteCount: 3, createdAt: '2026-05-29T09:00:00Z' },
    { id: 'c5', postId: 'p2', userId: 'u14', displayName: 'u/BerlinLocal', content: 'That\'s normal for nice restaurants in Mitte tbh. You get what you pay for.', upvoteCount: 34, downvoteCount: 8, createdAt: '2026-05-29T09:30:00Z' },
  ],
};

export const COSTLIEST_BY_CITY: Record<string, PartnerNameStat[]> = {
  Berlin: [
    { name: 'Sven', avgCents: 11800, entryCount: 234, happyPct: 72, city: 'Berlin' },
    { name: 'Laura', avgCents: 10900, entryCount: 189, happyPct: 68, city: 'Berlin' },
    { name: 'Jan', avgCents: 10200, entryCount: 156, happyPct: 81, city: 'Berlin' },
    { name: 'Tim', avgCents: 9800, entryCount: 142, happyPct: 75, city: 'Berlin' },
    { name: 'Mia', avgCents: 9200, entryCount: 127, happyPct: 85, city: 'Berlin' },
    { name: 'Julia', avgCents: 8700, entryCount: 118, happyPct: 79, city: 'Berlin' },
  ],
  Munich: [
    { name: 'Sabrina', avgCents: 13200, entryCount: 198, happyPct: 78, city: 'Munich' },
    { name: 'Klaus', avgCents: 12100, entryCount: 167, happyPct: 65, city: 'Munich' },
    { name: 'Robert', avgCents: 11400, entryCount: 145, happyPct: 82, city: 'Munich' },
    { name: 'Maximilian', avgCents: 10800, entryCount: 134, happyPct: 74, city: 'Munich' },
    { name: 'Sven', avgCents: 10200, entryCount: 123, happyPct: 71, city: 'Munich' },
    { name: 'Jens', avgCents: 9600, entryCount: 109, happyPct: 77, city: 'Munich' },
  ],
  Hamburg: [
    { name: 'Emma', avgCents: 10500, entryCount: 176, happyPct: 89, city: 'Hamburg' },
    { name: 'Felix', avgCents: 9800, entryCount: 154, happyPct: 73, city: 'Hamburg' },
    { name: 'Hannah', avgCents: 9200, entryCount: 138, happyPct: 80, city: 'Hamburg' },
    { name: 'Leon', avgCents: 8700, entryCount: 121, happyPct: 76, city: 'Hamburg' },
    { name: 'Lena', avgCents: 8100, entryCount: 108, happyPct: 83, city: 'Hamburg' },
  ],
  Cologne: [
    { name: 'Marie', avgCents: 9800, entryCount: 143, happyPct: 84, city: 'Cologne' },
    { name: 'Stefan', avgCents: 9200, entryCount: 128, happyPct: 70, city: 'Cologne' },
    { name: 'Anna', avgCents: 8600, entryCount: 115, happyPct: 87, city: 'Cologne' },
    { name: 'Lukas', avgCents: 8100, entryCount: 102, happyPct: 74, city: 'Cologne' },
  ],
  Frankfurt: [
    { name: 'Sophie', avgCents: 12400, entryCount: 189, happyPct: 76, city: 'Frankfurt' },
    { name: 'Tobias', avgCents: 11200, entryCount: 156, happyPct: 68, city: 'Frankfurt' },
    { name: 'Lisa', avgCents: 10600, entryCount: 134, happyPct: 82, city: 'Frankfurt' },
    { name: 'Michael', avgCents: 9900, entryCount: 121, happyPct: 73, city: 'Frankfurt' },
    { name: 'Katrin', avgCents: 9200, entryCount: 108, happyPct: 79, city: 'Frankfurt' },
  ],
};

export const TRENDING_NAMES = {
  byCost: [
    { name: 'Sabrina', avgCents: 13200, entryCount: 198, happyPct: 78 },
    { name: 'Klaus', avgCents: 12100, entryCount: 167, happyPct: 65 },
    { name: 'Sophie', avgCents: 11800, entryCount: 234, happyPct: 76 },
    { name: 'Robert', avgCents: 11400, entryCount: 145, happyPct: 82 },
    { name: 'Sven', avgCents: 11200, entryCount: 189, happyPct: 72 },
    { name: 'Maximilian', avgCents: 10800, entryCount: 134, happyPct: 74 },
  ],
  byHappy: [
    { name: 'Emma', avgCents: 10500, entryCount: 176, happyPct: 89 },
    { name: 'Anna', avgCents: 8600, entryCount: 115, happyPct: 87 },
    { name: 'Marie', avgCents: 9800, entryCount: 143, happyPct: 84 },
    { name: 'Lena', avgCents: 8100, entryCount: 108, happyPct: 83 },
    { name: 'Robert', avgCents: 11400, entryCount: 145, happyPct: 82 },
    { name: 'Hannah', avgCents: 9200, entryCount: 138, happyPct: 80 },
  ],
  byDates: [
    { name: 'Sophie', avgCents: 11800, entryCount: 423, happyPct: 76 },
    { name: 'Emma', avgCents: 10500, entryCount: 398, happyPct: 89 },
    { name: 'Sven', avgCents: 11200, entryCount: 356, happyPct: 72 },
    { name: 'Laura', avgCents: 10900, entryCount: 312, happyPct: 68 },
    { name: 'Felix', avgCents: 9800, entryCount: 289, happyPct: 73 },
    { name: 'Anna', avgCents: 8600, entryCount: 267, happyPct: 87 },
  ],
};

export const LIVE_FEED: TrendingEntry[] = [
  { activityType: 'food_date', amountCents: 18000, city: 'Berlin', minutesAgo: 2 },
  { activityType: 'coffee', amountCents: 1200, city: 'London', minutesAgo: 4 },
  { activityType: 'gift', amountCents: 15000, city: 'Paris', minutesAgo: 8 },
  { activityType: 'trip', amountCents: 420000, city: 'NYC', minutesAgo: 12 },
  { activityType: 'movie', amountCents: 3200, city: 'Munich', minutesAgo: 15 },
  { activityType: 'food_date', amountCents: 9500, city: 'Hamburg', minutesAgo: 19 },
  { activityType: 'coffee', amountCents: 800, city: 'Vienna', minutesAgo: 23 },
  { activityType: 'gift', amountCents: 8000, city: 'Amsterdam', minutesAgo: 28 },
];

export const PLATFORM_STATS = {
  totalEntries: 1847,
  totalSpentCents: 247_800_00,
  totalUsers: 395,
  onlineUsers: 4,
  avgSpendCents: 8700,
  moodHappyPct: 74,
  topActivity: 'Food Date',
  topCity: 'Berlin',
};
